### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire-python#11] opened 2015-08-12 15:17 UTC
It would be nice to simply:
  - pip install arrayfire
or as an intermediary:
  - pip install git+https://github.com/arrayfire/arrayfire-python

I think all it needs is a setup.py

**Comment by pavanky** [comment] 2015-08-12 15:23
duplicate of https://github.com/arrayfire/arrayfire-python/issues/8

**Closed by pavanky** 2015-08-12 15:23 UTC

**Comment by jramapuram** [comment] 2015-08-12 23:29
Gah I need to read, sorry. Did a quick grep for pip and didnt see anything.

**Comment by pavanky** [comment] 2015-08-31 10:13
@jramapuram It is now in master. Let me know if it works.
