### ISSUE TITLE
Vectorizing the operation

### ISSUE THREAD

**Issue by TejasMane** [arrayfire/arrayfire-python#127] opened 2017-02-17 08:56 UTC
Consider the following code segment:

```python
x_indices = af.Array([0,1,0])
y_indices = af.Array([1,1,2])
data = af.Array([0, 5, 10])
```

I want `A[0, 1] = data[0]`, `A[1,1] = data[1]` and `A[0, 2] = data[2]`. There are no patterns present in `x_indices` and `y_indices`.

Working Implementation

```python
for i in range(x_indices.elements()) # looping over the indices
    A[x_indices[i], y_indices[i]] = data[i] 
```

How can I **vectorize** the above operation. 

An similar operation in **numpy** can be done in the following manner:

`
A[x_indices, y_indices] = data
`

This would do the required operation:
`A[0, 1] = data[0]`, `A[1,1] = data[1]` and `A[0, 2] = data[2]`

But the arrayfire implementation does **not** seem to do the same. How can I perform this vectorized assignment using arrayfire.

**Comment by FilipeMaia** [comment] 2017-02-17 09:05
As far as I know this is currently not possible. It also prevents me from implementing numpy fancy indexing with multiple arrays (what you described) in afnumpy.

**Comment by TejasMane** [comment] 2017-02-17 09:18
Thanks, Any smarter workarounds for the same, besides converting the Arrayfire arrays to numpy arrays?

**Comment by pavanky** [comment] 2017-02-17 09:30
@TejasMane I assume you are a colleague of @ShyamSS-95 (I am assuming because you forked one of his repos).

He opened an issue about the same topic yesterday: https://github.com/arrayfire/arrayfire-python/issues/126. I am closing this issue, please focus the discussion over there.

Please read through my comments.

@FilipeMaia Hmm, this is indeed tricky. The indexing in the python wrapper is a bit mixed (follows a bit of traditional python and a little bit of arrayfire-isms) at the moment. Do you think it would be ok if I added a function that performs this operation instead of using the operator ?

**Closed by pavanky** 2017-02-17 09:30 UTC

**Comment by FilipeMaia** [comment] 2017-02-17 09:39
Sure, that would be helpful. It might even be useful to do it on the C side.

**Comment by pavanky** [comment] 2017-02-17 09:45
@FilipeMaia It is supported in C side. Python behaves differently from C because all missing dimensions in python are assumed to be spans.. Where as in C they are assumed to be 0.

**Comment by FilipeMaia** [comment] 2017-02-17 10:16
@pavanky The problem is not the missing dimensions, but the way the arrays are combined.

For example if one has [0,1],[0,1] as the two arrays for numpy this would mean that the coordinates retrieved would be [0,0], [1,1] while for arrayfire it would be [0,0], [0,1], [1,0], [1,1].

How to get the first behaviour using the C API?

**Comment by pavanky** [comment] 2017-02-17 10:28
@FilipeMaia I understand the basic problem. I was talking about the work around we use in C / C++, i.e. you can do `A(y * A.dims(0) + x) = val` to do the numpy equivalent of `A[x, y] = val`. 

However when you do `A[y * A.dims(0) + x] = val` in arrayfire python, it becomes the C++ equivalent of `A(y * A.dims(0) + x, span) = val`.

**Comment by FilipeMaia** [comment] 2017-02-17 10:34
@pavanky Ah ok, understood. But to reiterate, yes a python function to do this would be useful.
