### ISSUE TITLE
Output does not display in ipython notebook

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire-python#49] opened 2015-12-11 22:34 UTC
Trying to do:

```
import arrayfire as af
a = af.randu(10)
af.display(a)
```

prints to the terminal from which ipython notebook has been opened instead of the output cells in ipython.

**Comment by pavanky** [comment] 2015-12-11 22:40
@mchandra Is this an issue if you used `print(a)` as well ? The only difference between `af.display` and `print` is that `af.display` tries to print the variable name when it can.

**Comment by mchandra** [comment] 2015-12-11 22:43
I just updated arrayfire-python and now the above works. However

```
af.info()
```

still displays the output in the terminal and not the ipython output cell.

**Comment by pavanky** [comment] 2015-12-11 22:48
@mchandra That is a problem. `af.info()` does not return a string. It just prints it to the console. The problem is upstream with arrayfire. I just created [this issue](https://github.com/arrayfire/arrayfire/issues/1159) to deal with it.

I will update this repo once that feature goes into arrayfire.

**Comment by pavanky** [comment] 2015-12-11 22:48
I am closing this issue and opening a new one for `af.info()`

**Closed by pavanky** 2015-12-11 22:48 UTC
